### ISSUE TITLE
Perfect Pixel

### ISSUE THREAD

**Issue by Feinminen** [vovnet/fsd#1]
Выложить изображение, по которому подгонялся Perfect Pixel, а также скриншот с настройками.

**Comment by vovnet** [comment]
Изображения всех страниц нужны?
И скриншот с какими настройками?

**Comment by Feinminen** [comment]
Да, всех страниц, чтобы была возможность проверить все странички.
![image](https://user-images.githubusercontent.com/44312820/71524832-d4cafb80-2901-11ea-95bc-5a91b8554c39.png)
Скриншот настроек PP. Для того чтобы при проверке масштаб был одинаковый и сдвиги(если они есть)
