### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by viktoriya-ch** [vovnet/fsd#27]
Всё, что относится к БЭМ-блоку, должно быть описано в его собственных файлах, а у тебя элемент `.main-layout__kit` оказался в файле cards.pug.

![Снимок экрана от 2020-05-19 12-29-48](https://user-images.githubusercontent.com/38564412/82310130-ac38c080-99cc-11ea-80b2-6d8d17465afa.png)

**Comment by viktoriya-ch** [comment]
bullet - это же блок? Почему его описание лежит в блоке room-details?

![Снимок экрана от 2020-05-19 12-46-17](https://user-images.githubusercontent.com/38564412/82311796-d8edd780-99ce-11ea-8270-9d5f0feceff4.png)

**Comment by viktoriya-ch** [comment]
Когда именуем классы с префиксом js, название формируется путем простого добавления префикса к классу. То есть здесь если отбросить префикс, получается, что блок называется `button`. И такой блок не имеет отношения к блоку `icon-button`. К тому же, опять нарушается независимость, поскольку к `js-button` обращение идет откуда-то извне.

![Снимок экрана от 2020-05-19 14-49-41](https://user-images.githubusercontent.com/38564412/82323343-959c6480-99e0-11ea-82eb-a6ffec78c0c3.png)

**Comment by vovnet** [comment]
> Когда именуем классы с префиксом js, название формируется путем простого добавления префикса к классу. То есть здесь если отбросить префикс, получается, что блок называется `button`. И такой блок не имеет отношения к блоку `icon-button`. К тому же, опять нарушается независимость, поскольку к `js-button` обращение идет откуда-то извне.
> 
> ![Снимок экрана от 2020-05-19 14-49-41](https://user-images.githubusercontent.com/38564412/82323343-959c6480-99e0-11ea-82eb-a6ffec78c0c3.png)

а как тогда правильно обратиться к этой кнопке, если мне нужно прослушивать событие клика для меню?

**Comment by viktoriya-ch** [comment]
> а как тогда правильно обратиться к этой кнопке, если мне нужно прослушивать событие клика для меню?

В зависимости от ситуации, иногда достаточно повесить обработчик на элемент соответствующего блока (если работаем с блоком menu, то на элемент menu__button какой-нибудь). 

А вообще в целом БЭМ описывает в доках, как мы можем взаимодействовать в js между разными блоками: для этого могут быть использованы публичные методы/подписки на события.

> Блоки могут взаимодействовать друг с другом с помощью:
Подписки на события других экземпляров блоков.
Подписки на изменения модификаторов.
Непосредственного вызова методов других экземпляров блоков или статических методов класса другого блока.
Любых паттернов взаимодействия. Например, канала событий: все коммуникации происходят благодаря сообщениям, которые компоненты публикуют и слушают с помощью посредника.

https://ru.bem.info/methodology/js/#%D0%92%D0%B7%D0%B0%D0%B8%D0%BC%D0%BE%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%BE%D0%B2

**Comment by viktoriya-ch** [comment]
Это модификатор или элемент? Если модификатор, то по БЭМ он не может существовать без элемента, а если элемент, то не соблюдено соглашение по именованию элементов:

![Снимок экрана от 2020-05-19 15-16-09](https://user-images.githubusercontent.com/38564412/82325365-cf229f00-99e3-11ea-89be-ee10e96dccbc.png)

**Comment by viktoriya-ch** [comment]
`.mark` - это какой-то посторонний блок или от какого-то плагина класс, или откуда это?

![Снимок экрана от 2020-05-19 15-36-50](https://user-images.githubusercontent.com/38564412/82327166-ac45ba00-99e6-11ea-8b43-ca5eb5bcb2bf.png)

**Comment by viktoriya-ch** [comment]
Насчет имен элементов не соглашусь - по БЭМ имя элемента - существительное, а не прилагательное. У тебя где-то еще в проекте встречаются элементы `__left` и `__right`, их тоже стоит заодно поправить, чтобы закрепить знание.

https://github.com/vovnet/fsd/blob/e0756b186240621a3328ff7ece3bcd492e255778/src/blocks/price/price.pug#L2-L4
