### ISSUE TITLE
FormElements

### ISSUE THREAD

**Issue by viktoriya-ch** [vovnet/fsd#29]
А почему тут все настройки захардкожены, это чтобы что-то поменять, нужно будет прямо в init() лезть, и там переделывать?

![Снимок экрана от 2020-05-19 12-50-37](https://user-images.githubusercontent.com/38564412/82312244-76e1a200-99cf-11ea-81bf-37e62187a9e7.png)

**Comment by viktoriya-ch** [comment]
Что это за селекторы, где они берутся? Из каких-то других блоков? По идее у тебя блоки должны быть полностью независимы, и один блок не должен напрямую лезть в другой:

![Снимок экрана от 2020-05-19 12-51-56](https://user-images.githubusercontent.com/38564412/82312430-b3ad9900-99cf-11ea-8dff-9781533aaa3f.png)

**Comment by viktoriya-ch** [comment]
В проекте есть и другие классы, в которых аналогичная реализация.

**Comment by viktoriya-ch** [comment]
Еще примеры захардкоженности - у слайдера вшиты параметры:

![Снимок экрана от 2020-05-19 15-27-00](https://user-images.githubusercontent.com/38564412/82326317-486ec180-99e5-11ea-9243-1bce7c2154d0.png)

**Comment by vovnet** [comment]
> А почему тут все настройки захардкожены, это чтобы что-то поменять, нужно будет прямо в init() лезть, и там переделывать?
> 
> ![Снимок экрана от 2020-05-19 12-50-37](https://user-images.githubusercontent.com/38564412/82312244-76e1a200-99cf-11ea-81bf-37e62187a9e7.png)

так это же и есть настройка плагина в конкретных блоках, или нужно чтобы эти значения приходили прямо в миксин?

**Comment by viktoriya-ch** [comment]
> так это же и есть настройка плагина в конкретных блоках, или нужно чтобы эти значения приходили прямо в миксин?

Ну это довольно странно, что для того, чтобы поменять слово "младенцы" на "дети до года", тебе придется копаться в реализации класса.

На реальном проекте у тебя вообще все тексты могут в одном файле храниться, а блоки только переменные например будут использовать.

**Comment by vovnet** [comment]
> > так это же и есть настройка плагина в конкретных блоках, или нужно чтобы эти значения приходили прямо в миксин?
> 
> Ну это довольно странно, что для того, чтобы поменять слово "младенцы" на "дети до года", тебе придется копаться в реализации класса.
> 
> На реальном проекте у тебя вообще все тексты могут в одном файле храниться, а блоки только переменные например будут использовать.

а как лучше сделать в моем случае?

**Comment by viktoriya-ch** [comment]
> а как лучше сделать в моем случае?

Вообще, сейчас еще подумала, наверное, лучше оставить как есть) Всё-таки если выносить в pug, слишком много настроек, вряд ли это упростит жизнь.

Это касается только классов, инициализирующих страницы, у Slider другая история, там точно надо править.

**Comment by viktoriya-ch** [comment]
И вопрос по поводу того, что ты обращаешься к каким-то классам вне блока, тоже остается. Если есть вопросы-предложения - пиши.

**Comment by vovnet** [comment]
> И вопрос по поводу того, что ты обращаешься к каким-то классам вне блока, тоже остается. Если есть вопросы-предложения - пиши.

Тут проблема с инициализацией - приходится задавать стартовые параметры дропдауна только через js и чтобы отличать один дропдаун от другого на странице, то приходится прокидывать в миксин какой-нибудь класс, а после доставать его через js и создавать дропдаун (new Dropdown), прокидывая туда этот контейнер. Ну что-бы это исправить, придется все переделать на data-атрибуты. Пока другого способа решения проблемы не вижу((

**Comment by vovnet** [comment]
Как вариант - просто искать инпут в контейнере и уже его инициализировать

**Comment by viktoriya-ch** [comment]
> Тут проблема с инициализацией - приходится задавать стартовые параметры дропдауна только через js и чтобы отличать один дропдаун от другого на странице, то приходится прокидывать в миксин какой-нибудь класс, а после доставать его через js и создавать дропдаун (new Dropdown), прокидывая туда этот контейнер.

Если я правильно поняла задачу

Почему бы не сделать, например, так:
1. Обернуть `.configuration-dropdown` в `.form-elements__configuration-dropdown`
2. В `new Dropdown()` прокинуть параметром элемент `.form-elements__configuration-dropdown`
3. Класс Dropdown у себя внутри принимает элемент, и в этом элементе уже ищет всё, что ему надо: свои инпуты и т.д. Так инкапсуляция не нарушится и каждый компонент будет знать только про собственные элементы.
