### ISSUE TITLE
Деструктуризация и другие мелочи

### ISSUE THREAD

**Issue by Feinminen** [vovnet/fsd#8]
По бэстпрактис необходимо доставать свойства объектов с помощью деструктурицазии, так код выглядит гораздо чище.Также рекомендуется добавлять классы всем элементам, даже если стилей у них нет. Т.к. классы добавляют семантичности. Инклюды необходимо выносить в самое начало файла.
![image](https://user-images.githubusercontent.com/44312820/72534864-2257da00-38aa-11ea-9328-da2776bc7336.png)
Также если у тебя миксин comment, то внутри себя он может описывать только себя, другие блоки могут только инклюдиться.
У тебя в проекте avatar сам по себе ничего не представляет и используется только в одном месте. Имхо, лучше сделать аватрар не блоком, а элементом коммента.

**Comment by vovnet** [comment]
>  Также если у тебя миксин comment, то внутри себя он может описывать только себя, другие блоки могут только инклюдиться.

На скрине я же заинклюдил like или нужно как-то по-другому?

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/73747932-0c438800-478b-11ea-826b-4396dbde1988.png)
Также по прежнему есть элементы без классов.
